### ISSUE TITLE
Create new avatar style Error

### ISSUE THREAD

**Issue by gjssss** [dicebear/dicebear#252]
When I try to run `dicebear project new test`, it responds a 404 code.
```
C:\Users\...\>dicebear project new test
(node:7784) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\...\AppData\Roaming\npm\node_modules\dicebear\node_modules\tslib\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
| Download and extract templateC:\...\AppData\Roaming\npm\node_modules\dicebear\node_modules\got\index.js:482
                        proxy.emit('error', new got.HTTPError(statusCode, res.statusMessage, res.headers, opts), null, res);
                                            ^

GotError [HTTPError]: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (C:\...\AppData\Roaming\npm\node_modules\dicebear\node_modules\got\index.js:482:24)
    at EventEmitter.emit (node:events:527:28)
    at getResponse (C:\...\AppData\Roaming\npm\node_modules\dicebear\node_modules\got\index.js:320:5)
    at Immediate.<anonymous> (C:\...\AppData\Roaming\npm\node_modules\dicebear\node_modules\got\index.js:147:6)
    at processImmediate (node:internal/timers:466:21) {
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/dicebear/template/archive/refs/heads/main.zip',
  protocol: 'https:',
  url: 'https://github.com/dicebear/template/archive/refs/heads/main.zip',
  statusCode: 404,
  statusMessage: 'Not Found',
  headers: {
    server: 'GitHub.com',
    date: 'Wed, 04 Jan 2023 03:26:28 GMT',
    'content-type': 'text/plain; charset=utf-8',
    vary: 'X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With',
    'cache-control': 'no-cache',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'x-frame-options': 'deny',
    'x-content-type-options': 'nosniff',
    'x-xss-protection': '0',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    'content-security-policy': "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
    'content-encoding': 'gzip',
    'content-length': '29',
    'x-github-request-id': 'FFA1:4ED5:219EEC:28AB41:63B4F1E3',
    connection: 'close'
  }
}
```

**Comment by FlorianKoerner** [comment]
Hi @gjssss 

The script wants to download a template repository that I unfortunately deleted some time ago because it was outdated and (I thought) not used.

The `project` commands are deprecated and will not be supported in the next major version.

I can recommend you to take a look at the easiest avatar style [identicons](https://github.com/dicebear/dicebear/tree/main/packages/%40dicebear/avatars-identicon-sprites) or use the [Figma Exporter](https://github.com/dicebear/dicebear/discussions/161#discussioncomment-1368258).

In 1 to 2 weeks the next major version will be released along with new documentation. It will also have video instructions on how to create your own avatar style via Figma.

If your avatar style is made available under MIT license, I'll be happy to help with the implementation as well.
