### ISSUE TITLE
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined

### ISSUE THREAD

**Issue by CSFlorin** [dicebear/dicebear#321]
Using Remix (which uses esbuild), React, and TypeScript, I get the following error:

```
TypeError: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at createRequire (node:internal/modules/cjs/loader:1373:11)
    at Object.<anonymous> (/Users/f/project/node_modules/@dicebear/converter/lib/utils/package-helper.js:2:17)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at /Users/f/project/node_modules/@remix-run/serve/dist/index.js:43:17
```

It happens at this code in @dicebear/converter/lib/utils/package-helper.js:

```
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
```

I confirmed that esbuild supports import.meta.url https://github.com/evanw/esbuild/issues/208 however remix does not seem to https://github.com/remix-run/remix/discussions/2607 Therefore, maybe there is a fix to default to an alternative?

Here is a full reproduction: https://stackblitz.com/edit/remix-run-remix-prf5l5?file=remix.config.js,app%2Froutes%2F_index.tsx

**Comment by CSFlorin** [comment]
I confirmed just replacing `import.meta.url` with `__dirname` fixes it!

**Comment by FlorianKoerner** [comment]
Hi @CSFlorin 

Although the problem is with Remix, removed corresponding code because it was optional anyway. Should work now with.
